export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_REPOS = 'GET_REPOS'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const PROFILE_ERROR = 'PROFIL_ERROR'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const POST_ERROR = 'POST_ERROR'
export const UPDATE_LIKES = 'UPDATE_LIKES'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

// entries
export const GET_ENTRIES = 'GET_ENTRIES'
export const ENTRY_ERROR = 'ENTRY_ERROR'
export const DELETE_ENTRY = 'DELETE_ENTRY'
export const ADD_ENTRY = 'ADD_ENTRY'
export const GET_ENTRY = 'GET_ENTRY'
export const RECEIVE_ENTRIES = ' RECEIVE_ENTRIES'

// authors
export const GET_AUTHORS = 'GET_AUTHORS'
export const AUTHOR_ERROR = 'AUTHOR_ERROR'
export const DELETE_AUTHOR = 'DELETE_AUTHOR'
export const ADD_AUTHOR = 'ADD_AUTHOR'
export const GET_AUTHOR = 'GET_AUTHOR'
export const RECEIVE_AUTHORS = ' RECEIVE_AUTHORS'
